export const C2S_EVENTS: {
  readonly JOIN_RADAR_ROOM: "join_radar_room";
  readonly LEAVE_RADAR_ROOM: "leave_radar_room";
  readonly CREATE_POKER_ROOM: "create_poker_room";
  readonly JOIN_POKER_ROOM: "join_poker_room";
  readonly RECONNECT_POKER_ROOM: "reconnect_poker_room";
  readonly LEAVE_POKER_ROOM: "leave_poker_room";
  readonly START_POKER_SESSION: "start_poker_session";
  readonly SET_VOTE_SYSTEM: "set_vote_system";
  readonly SET_POKER_ROLE: "set_poker_role";
  readonly VOTE_CARD: "vote_card";
  readonly REVEAL_VOTES: "reveal_votes";
  readonly OPEN_VOTES: "open_votes";
  readonly REVOTE_CURRENT_STORY: "revote_current_story";
  readonly REOPEN_STORY_VOTE: "reopen_story_vote";
  readonly RESET_VOTES: "reset_votes";
  readonly SET_STORY_TITLE: "set_story_title";
  readonly SELECT_POKER_STORY: "select_poker_story";
  readonly CREATE_ROOM: "create_room";
  readonly JOIN_ROOM: "join_room";
  readonly RECONNECT_ROOM: "reconnect_room";
  readonly LEAVE_ROOM: "leave_room";
  readonly START_GAME: "start_game";
  readonly ROLL_DICE: "roll_dice";
  readonly MOVE_PLAYER: "move_player";
  readonly CHOOSE_PATH: "choose_path";
  readonly RESOLVE_KUDO_PURCHASE: "resolve_kudo_purchase";
  readonly OPEN_SHOP: "open_shop";
  readonly CLOSE_SHOP: "close_shop";
  readonly BUY_SHOP_ITEM: "buy_shop_item";
  readonly USE_SHOP_ITEM: "use_shop_item";
  readonly POINT_DUEL_ROLL: "point_duel_roll";
  readonly RESOLVE_PRE_ROLL_CHOICE: "resolve_pre_roll_choice";
  readonly VOTE_QUESTION: "vote_question";
  readonly OPEN_QUESTION: "open_question";
  readonly VALIDATE_QUESTION: "validate_question";
  readonly BUG_SMASH_COMPLETE: "BUG_SMASH_COMPLETE";
  readonly BUG_SMASH_PROGRESS: "BUG_SMASH_PROGRESS";
  readonly BUZZWORD_SUBMIT: "BUZZWORD_SUBMIT";
  readonly WSI_SUBMIT: "WSI_SUBMIT";
  readonly NEXT_TURN: "next_turn";
  readonly RESET_GAME: "reset_game";
};

export const S2C_EVENTS: {
  readonly SERVER_HELLO: "server_hello";
  readonly RADAR_ROOM_JOINED: "radar_room_joined";
  readonly POKER_ROOM_CREATED: "poker_room_created";
  readonly POKER_ERROR_MESSAGE: "poker_error_msg";
  readonly POKER_ROOM_RECONNECTED: "poker_room_reconnected";
  readonly POKER_ROOM_JOINED: "poker_room_joined";
  readonly ROOM_CREATED: "room_created";
  readonly ERROR_MESSAGE: "error_msg";
  readonly ROOM_RECONNECTED: "room_reconnected";
  readonly ROOM_JOINED: "room_joined";
  readonly POKER_STATE_UPDATE: "poker_state_update";
  readonly POKER_LOBBY_UPDATE: "poker_lobby_update";
  readonly POKER_ROOM_CLOSED: "poker_room_closed";
  readonly WSI_ROUND_REVEAL: "WSI_ROUND_REVEAL";
  readonly MINIGAME_END: "MINIGAME_END";
  readonly WSI_ROUND_START: "WSI_ROUND_START";
  readonly MINIGAME_START: "MINIGAME_START";
  readonly STATE_UPDATE: "state_update";
  readonly LOBBY_UPDATE: "lobby_update";
  readonly ROOM_CLOSED: "room_closed";
  readonly RADAR_SESSION_UPDATE: "radar_session_update";
};

export type ClientToServerEvent = (typeof C2S_EVENTS)[keyof typeof C2S_EVENTS];
export type ServerToClientEvent = (typeof S2C_EVENTS)[keyof typeof S2C_EVENTS];
