export const RADAR_QUESTIONS = [
  { id: 1, text: "Notre vision produit est claire et partagee par l'equipe.", dimension: "visionStrategy", subdimension: "Vision & Purpose" },
  { id: 2, text: "Nous comprenons bien les besoins reels de nos clients.", dimension: "visionStrategy", subdimension: "Customer Focus" },
  { id: 3, text: "Nous utilisons des objectifs explicites pour guider nos choix.", dimension: "visionStrategy", subdimension: "Goals & Outcomes" },
  { id: 4, text: "Nous prenons le temps d'experimenter de nouvelles approches.", dimension: "visionStrategy", subdimension: "Learning & Experimenting" },
  { id: 5, text: "Nous favorisons la creativite et l'innovation dans l'equipe.", dimension: "visionStrategy", subdimension: "Creativity & Innovation" },
  { id: 6, text: "Nos choix strategiques sont coherents avec la valeur attendue.", dimension: "visionStrategy", subdimension: "Strategic Alignment" },
  { id: 7, text: "Nous savons expliquer pourquoi une priorite est retenue.", dimension: "visionStrategy", subdimension: "Prioritization Logic" },
  { id: 8, text: "Les retours de terrain influencent reellement notre direction.", dimension: "visionStrategy", subdimension: "Feedback Integration" },
  { id: 9, text: "Nous adaptons notre strategie quand les signaux changent.", dimension: "visionStrategy", subdimension: "Strategic Adaptability" },
  { id: 10, text: "Notre feuille de route reste lisible meme quand le contexte evolue.", dimension: "visionStrategy", subdimension: "Roadmap Clarity" },

  { id: 11, text: "Nous decoupons bien le travail en objectifs court terme atteignables.", dimension: "planning", subdimension: "Short-Term Plan" },
  { id: 12, text: "Nos priorites sont ordonnees de facon transparente.", dimension: "planning", subdimension: "Prioritization Breakdown" },
  { id: 13, text: "Nous maintenons une roadmap realiste et actualisee.", dimension: "planning", subdimension: "Roadmap" },
  { id: 14, text: "Les dependances et risques sont identifies en amont.", dimension: "planning", subdimension: "Risk Anticipation" },
  { id: 15, text: "Les responsabilites sont claires avant de lancer une iteration.", dimension: "planning", subdimension: "Roles & Skills" },
  { id: 16, text: "Les outils supports nous aident vraiment a planifier.", dimension: "planning", subdimension: "Tools" },
  { id: 17, text: "Nous estimons la charge avec un niveau de precision suffisant.", dimension: "planning", subdimension: "Capacity Planning" },
  { id: 18, text: "Nos plans restent comprehensibles pour toutes les parties prenantes.", dimension: "planning", subdimension: "Stakeholder Visibility" },
  { id: 19, text: "Nous preparons les sessions de planification de facon efficace.", dimension: "planning", subdimension: "Planning Hygiene" },
  { id: 20, text: "Nous revisons regulierement le plan plutot que de le figer.", dimension: "planning", subdimension: "Plan Adaptation" },

  { id: 21, text: "Nos rituels d'equipe sont utiles et bien animes.", dimension: "execution", subdimension: "Effective Meetings" },
  { id: 22, text: "Les decisions operationnelles sont prises sans lenteur inutile.", dimension: "execution", subdimension: "Operational Decision-Making" },
  { id: 23, text: "Nous suivons des metriques pertinentes pour piloter l'execution.", dimension: "execution", subdimension: "Metrics" },
  { id: 24, text: "Nous supprimons rapidement les obstacles qui bloquent l'equipe.", dimension: "execution", subdimension: "Obstacle Removal" },
  { id: 25, text: "Nous gardons une cadence de livraison stable.", dimension: "execution", subdimension: "Delivery Rhythm" },
  { id: 26, text: "La qualite d'execution reste constante sprint apres sprint.", dimension: "execution", subdimension: "Execution Consistency" },
  { id: 27, text: "Nos engagements sont tenus avec un bon niveau de fiabilite.", dimension: "execution", subdimension: "Reliability" },
  { id: 28, text: "Nous ajustons vite notre facon de faire quand un probleme revient.", dimension: "execution", subdimension: "Continuous Improvement" },
  { id: 29, text: "Nous faisons circuler l'information utile au bon moment.", dimension: "execution", subdimension: "Operational Transparency" },
  { id: 30, text: "Nos actions quotidiennes restent alignees avec le plan.", dimension: "execution", subdimension: "Plan Execution" },

  { id: 31, text: "Les membres de l'equipe se sentent engages dans les objectifs communs.", dimension: "mindsetBehaviors", subdimension: "Engaged & Motivated" },
  { id: 32, text: "Nous laissons de l'autonomie pour prendre des initiatives.", dimension: "mindsetBehaviors", subdimension: "Autonomy" },
  { id: 33, text: "Le respect et la confiance sont visibles dans nos interactions.", dimension: "mindsetBehaviors", subdimension: "Trust & Respect" },
  { id: 34, text: "Nous prenons soin de l'equilibre et du bien-etre de l'equipe.", dimension: "mindsetBehaviors", subdimension: "Well-Being" },
  { id: 35, text: "Le climat de securite psychologique favorise la prise de parole.", dimension: "mindsetBehaviors", subdimension: "Psychological Safety" },
  { id: 36, text: "Nous avons des conversations constructives meme en cas de desaccord.", dimension: "mindsetBehaviors", subdimension: "Constructive Conversations" },
  { id: 37, text: "La diversite des points de vue est valorisee.", dimension: "mindsetBehaviors", subdimension: "Diversity & Inclusion" },
  { id: 38, text: "Chacun prend sa part de responsabilite sur les resultats collectifs.", dimension: "mindsetBehaviors", subdimension: "Accountability & Ownership" },
  { id: 39, text: "Le feedback et la reconnaissance sont regulierement pratiques.", dimension: "mindsetBehaviors", subdimension: "Feedback & Recognition" },
  { id: 40, text: "Nous cooperons de facon ouverte entre les profils et metiers.", dimension: "mindsetBehaviors", subdimension: "Open & Collaborative" },
];
