export const WHO_SAID_IT_ROLES = ["MANAGER", "PO", "DEV", "SCRUM_MASTER", "QA_SUPPORT"];

export const whoSaidItBank = [
  { id: "1", text: "On livrera d'abord, on testera apres.", answer: "MANAGER" },
  { id: "2", text: "C'est juste un petit changement, ca prend 5 minutes.", answer: "PO" },
  { id: "3", text: "Ca marche sur ma machine.", answer: "DEV" },
  { id: "4", text: "On pourrait peut-etre en parler en retro ?", answer: "SCRUM_MASTER" },
  { id: "5", text: "Je viens de trouver un bug bloquant en prod.", answer: "QA_SUPPORT" },
  { id: "6", text: "On peut ajouter cette feature au sprint en cours ?", answer: "PO" },
  { id: "7", text: "Il faut aller plus vite avec plus de developpeurs.", answer: "MANAGER" },
  { id: "8", text: "On n'a pas besoin de documentation.", answer: "DEV" },
  { id: "9", text: "Le WIP est un peu eleve non ?", answer: "SCRUM_MASTER" },
  { id: "10", text: "Les tests de non-regression ne sont pas passes.", answer: "QA_SUPPORT" },
  { id: "11", text: "On peut livrer vendredi, coute que coute.", answer: "MANAGER" },
  { id: "12", text: "Le client veut absolument cette feature pour hier.", answer: "PO" },
  { id: "13", text: "On peut refactoriser plus tard.", answer: "DEV" },
  { id: "14", text: "On a bien respecte la Definition of Done ?", answer: "SCRUM_MASTER" },
  { id: "15", text: "Je reproduis le bug 1 fois sur 3.", answer: "QA_SUPPORT" },
  { id: "16", text: "Pourquoi on fait des retrospectives deja ?", answer: "MANAGER" },
  { id: "17", text: "On pourrait splitter la story en deux.", answer: "PO" },
  { id: "18", text: "On peut pousser en prod, ca devrait passer.", answer: "DEV" },
  { id: "19", text: "Restons focus sur l'objectif du sprint.", answer: "SCRUM_MASTER" },
  { id: "20", text: "Le bug est critique, il bloque tout le parcours.", answer: "QA_SUPPORT" },
  { id: "21", text: "On augmentera le budget si necessaire.", answer: "MANAGER" },
  { id: "22", text: "Ce n'est pas dans le backlog prioritaire.", answer: "PO" },
  { id: "23", text: "Ca fonctionne en local pourtant.", answer: "DEV" },
  { id: "24", text: "Qui est volontaire pour animer la daily demain ?", answer: "SCRUM_MASTER" },
  { id: "25", text: "Le scenario de test ne passe pas.", answer: "QA_SUPPORT" },
  { id: "26", text: "On fera les tests automatises plus tard.", answer: "MANAGER" },
  { id: "27", text: "On peut re-prioriser en cours de sprint ?", answer: "PO" },
  { id: "28", text: "La dette technique commence a piquer.", answer: "DEV" },
  { id: "29", text: "Le sprint est un engagement, pas une promesse magique.", answer: "SCRUM_MASTER" },
  { id: "30", text: "Je valide la recette sous reserve d'un correctif.", answer: "QA_SUPPORT" },
  { id: "31", text: "Pourquoi ca prend autant de temps ?", answer: "MANAGER" },
  { id: "32", text: "On pourrait faire un spike technique avant.", answer: "PO" },
  { id: "33", text: "On merge direct sur la branche principale ?", answer: "DEV" },
  { id: "34", text: "On respecte bien le timebox ?", answer: "SCRUM_MASTER" },
  { id: "35", text: "Le ticket est incomplet pour tester.", answer: "QA_SUPPORT" },
  { id: "36", text: "On peut supprimer la daily pour gagner du temps.", answer: "MANAGER" },
  { id: "37", text: "La valeur business est prioritaire ici.", answer: "PO" },
  { id: "38", text: "Le code est un peu sale mais ca tourne.", answer: "DEV" },
  { id: "39", text: "On ameliore le process ou on continue comme ca ?", answer: "SCRUM_MASTER" },
  { id: "40", text: "J'ai besoin d'un environnement stable pour tester.", answer: "QA_SUPPORT" },
  { id: "41", text: "On ajoutera les indicateurs plus tard.", answer: "MANAGER" },
  { id: "42", text: "Cette story apporte beaucoup de valeur utilisateur.", answer: "PO" },
  { id: "43", text: "On peut optimiser ca en une ligne.", answer: "DEV" },
  { id: "44", text: "Qui bloque sur quoi aujourd'hui ?", answer: "SCRUM_MASTER" },
  { id: "45", text: "Il y a un edge case non couvert.", answer: "QA_SUPPORT" },
  { id: "46", text: "On verra ca en phase 2.", answer: "MANAGER" },
  { id: "47", text: "On ajuste le backlog avant le prochain sprint.", answer: "PO" },
  { id: "48", text: "Le build est rouge mais ca devrait passer.", answer: "DEV" },
  { id: "49", text: "On inspecte et on adapte.", answer: "SCRUM_MASTER" },
  { id: "50", text: "La correction a cree une regression ailleurs.", answer: "QA_SUPPORT" },
];
